name: Bates Westmoreland
url: http://www.rbwestmoreland.com
permalink: /posts/:title
paginate: 10

# GitHub Defaults
lsi: false
pygments: true
safe: true

# UTF-8 & parse errors fix
markdown: redcarpet